### PR TITLE
feat: Token transaction w/ partial sign snippet (#293)

### PR DESCRIPTION
**Pull request by mcintyre94**
- Intended to address discord question: https://discord.com/channels/428295358100013066/517163444747894795/953743912437166150
- Modified from a NextJS example: https://github.com/mcintyre94/solana-partially-signed

- I've used public/private keys from other code examples
- The token address I've used is the one from https://spl-token-faucet.com

The code creates a transaction where:
- Alice sends Bob 0.01 SOL
- Bob sends Alice 1 token
- Bob partially signs the transaction
- The transaction is serialized + returned

New snippet: https://solana-cookbook-git-fork-mcintyre94-token-tx-pa-b4aeb7-cookbook.vercel.app/references/offline-transactions.html#partial-sign-transaction

### CODE REVIEW

**Comment by jacobcreech** [comment]
🤔 I understand the example and what it is trying to convey, but isn't this kind of a weird place for showcasing backend-frontend signing of a transaction? Feels out of place in Token.

Thinking of discoverability too, I don't think someone having the question of "how do I sign a transaction on both backend and frontend" will be able to find this example, or even recognize it for what it is. WDYT?

It may be something to change the "offline transactions" reference into something that can fit both these needs. Naming is hard

**Comment by mcintyre94** [comment]
@jacobcreech Yep fair point! The way it was originally asked on Discord was about sending a token when someone sends you SOL. But it does apply to anything that requires Bob to be the signer in addition to Alice, and I agree that "how do I sign a transaction on both backend and frontend" is also a question this can be used to answer. 

Maybe it'd make sense to just call this "Partial Sign Transaction" and put it under "Sending offline transactions"?

**Comment by jacobcreech** [comment]
Yeah, let's call it `How to partial sign transactions` under `offline transactions` and add some more descriptions on use cases

**Comment by mcintyre94** [comment]
@jacobcreech Updated: new section is now at https://solana-cookbook-git-fork-mcintyre94-token-tx-pa-b4aeb7-cookbook.vercel.app/references/offline-transactions.html#partial-sign-transaction

**Review by jacobcreech — APPROVED** [review]
Looks great! Thanks for the contribution!

**Pull request merged**
