### PR TITLE
Changes based on feedback from Tao.

### PR DESCRIPTION
**Pull request by brianlong**
Changes based on feedback from Tao.

### CODE REVIEW

**Review by taozhu-chicago — APPROVED** [review]
lgtm

**Comment by brianlong** [comment]
@jacobcreech I think your CI pipeline to production is broken again...

**Comment by jacobcreech** [comment]
Dang thing keeps OOM'ing

**Comment by jacobcreech** [comment]
@brianlong live https://solanacookbook.com/references/basic-transactions.html#how-to-change-compute-budget-fee-priority-for-a-transaction

**Pull request merged**
